//=============================================================================
// CowRemap.
//=============================================================================
class CowFixModels expands Decoration;

//#exec MESH IMPORT MESH=TCowNewJRM ANIVFILE=Models\CowRemap_a.3d DATAFILE=Models\CowRemap_d.3d X=0 Y=0 Z=0 LODSTYLE=10 LODFRAME=0 
//#exec MESH ORIGIN MESH=TCowNewJRM X=0 Y=0 Z=0 YAW=-64 PITCH=0 ROLL=0


#exec MESH IMPORT MESH=TCowNewJRM ANIVFILE=Models\CowFixJohnny_a.3d DATAFILE=Models\CowFixJohnny_d.3d X=0 Y=0 Z=0 LODSTYLE=10 LODFRAME=0 
#exec MESH ORIGIN MESH=TCowNewJRM X=0 Y=0 Z=0 YAW=-64 PITCH=0 ROLL=0

#exec MESHMAP NEW MESHMAP=TCowNewJRM MESH=TCowNewJRM
//#exec MESHMAP SCALE MESHMAP=TCowNewJRM X=0.1 Y=0.1 Z=0.2


#exec MESHMAP SCALE MESHMAP=TCowNewJRM X=0.063 Y=0.0432  Z=0.126

#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=All     STARTFRAME=17    NUMFRAMES=249
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Breath1 STARTFRAME=17    NUMFRAMES=14  RATE=6	Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Breath1L STARTFRAME=17    NUMFRAMES=14  RATE=6	Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Breath3 STARTFRAME=17    NUMFRAMES=14  RATE=6	Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Chat1   STARTFRAME=31   NUMFRAMES=7  RATE=6	Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=GutHit  STARTFRAME=75   NUMFRAMES=1			GROUP=Takehit
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=LeftHit STARTFRAME=249   NUMFRAMES=1			GROUP=Takehit
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Taunt1  STARTFRAME=137   NUMFRAMES=21 RATE=15	Group=Gesture
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Thrust  STARTFRAME=137   NUMFRAMES=21 RATE=15	Group=Gesture
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Breath2 STARTFRAME=17   NUMFRAMES=14 RATE=6	Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Breath2L STARTFRAME=17   NUMFRAMES=14 RATE=6	Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Look    STARTFRAME=17   NUMFRAMES=14 RATE=15  Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=LookL   STARTFRAME=17   NUMFRAMES=14 RATE=15  Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Walk    STARTFRAME=250   NUMFRAMES=16 RATE=15S
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=WalkLg  STARTFRAME=250   NUMFRAMES=16 RATE=15
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=WalkLgFr STARTFRAME=250  NUMFRAMES=16 RATE=15 Group=MovingFire
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=WalkSm  STARTFRAME=250  NUMFRAMES=16 RATE=15
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=WalkSmFr STARTFRAME=250  NUMFRAMES=16 RATE=15 Group=MovingFire
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=TurnLg  STARTFRAME=250   NUMFRAMES=2  RATE=15
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=TurnSm  STARTFRAME=250   NUMFRAMES=2  RATE=15
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=RunLg   STARTFRAME=250   NUMFRAMES=16 RATE=27
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=RunLgFr STARTFRAME=250   NUMFRAMES=16 RATE=27	Group=MovingFire
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=RunSm   STARTFRAME=250   NUMFRAMES=16 RATE=27
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=RunSmFr STARTFRAME=250   NUMFRAMES=16 RATE=27	Group=MovingFire
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=DuckWlkL STARTFRAME=250  NUMFRAMES=16 RATE=15 Group=Ducking
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=DuckWlkS STARTFRAME=250  NUMFRAMES=16 RATE=15 Group=Ducking
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=HeadHit STARTFRAME=60    NUMFRAMES=1			GROUP=Takehit
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=RightHit STARTFRAME=41  NUMFRAMES=1			GROUP=Takehit
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Dead1   STARTFRAME=38   NUMFRAMES=21 RATE=15
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Dead2   STARTFRAME=59   NUMFRAMES=16 RATE=15
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Dead4   STARTFRAME=99   NUMFRAMES=14 RATE=15
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=BigHit  STARTFRAME=102  NUMFRAMES=1
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Dead3   STARTFRAME=75   NUMFRAMES=24 RATE=15
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Victory1 STARTFRAME=157  NUMFRAMES=20 RATE=15 Group=Gesture
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=CockGun STARTFRAME=228  NUMFRAMES=20 RATE=15  Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=CockGunL STARTFRAME=228  NUMFRAMES=20 RATE=15  Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Wave    STARTFRAME=189  NUMFRAMES=17 RATE=15  Group=Gesture
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=WaveL   STARTFRAME=189  NUMFRAMES=17 RATE=15  Group=Gesture
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=LandLgFr STARTFRAME=135  NUMFRAMES=1			Group=Landing
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=LandSmFr STARTFRAME=135  NUMFRAMES=1			Group=Landing
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Run 	  STARTFRAME=250  NUMFRAMES=16 RATE=20
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=BackRun STARTFRAME=0    NUMFRAMES=16 RATE=32  Group=MovingFire
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=StrafeL STARTFRAME=206  NUMFRAMES=11 RATE=20  Group=MovingFire
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=StrafeR STARTFRAME=217  NUMFRAMES=11 RATE=20  Group=MovingFire
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=SwimLg  STARTFRAME=178  NUMFRAMES=11 RATE=20
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=SwimSm  STARTFRAME=178  NUMFRAMES=11 RATE=20
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=TreadLg STARTFRAME=178  NUMFRAMES=11 RATE=15 Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=TreadSm STARTFRAME=178  NUMFRAMES=11 RATE=15 Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Fighter STARTFRAME=121  NUMFRAMES=1
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=AimDnLg STARTFRAME=124  NUMFRAMES=1			Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=AimDnSm STARTFRAME=124  NUMFRAMES=1			Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=AimUpLg STARTFRAME=124  NUMFRAMES=1			Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=AimUpSm STARTFRAME=124  NUMFRAMES=1			Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=StillFrRp STARTFRAME=132  NUMFRAMES=3	RATE=10		Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=StillLgFr STARTFRAME=122  NUMFRAMES=12	RATE=17			Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=StillSmFr STARTFRAME=122  NUMFRAMES=12	RATE=17			Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=JumpLgFr STARTFRAME=122  NUMFRAMES=1			Group=Jumping
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=JumpSmFr STARTFRAME=122  NUMFRAMES=1			Group=Jumping
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=DodgeB STARTFRAME=117  NUMFRAMES=1			Group=Jumping
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=DodgeF STARTFRAME=118  NUMFRAMES=1			Group=Jumping
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=DodgeR STARTFRAME=120  NUMFRAMES=1			Group=Jumping
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=DodgeL STARTFRAME=119  NUMFRAMES=1			Group=Jumping
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Flip   STARTFRAME=120  NUMFRAMES=3 Rate=15	Group=Jumping
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=DEAD9      STARTFRAME=97 NUMFRAMES=3

/*
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=All         STARTFRAME=0        NUMFRAMES=311                               // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Breath1     STARTFRAME=46       NUMFRAMES=16    RATE=6	    Group=Waiting   // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Breath1L    STARTFRAME=46       NUMFRAMES=16    RATE=6	    Group=Waiting   // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Breath3     STARTFRAME=46       NUMFRAMES=16    RATE=6	    Group=Waiting   // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Chat1       STARTFRAME=172      NUMFRAMES=11    RATE=6	    Group=Waiting   // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=GutHit      STARTFRAME=225      NUMFRAMES=1			        GROUP=Takehit   // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=LeftHit     STARTFRAME=226      NUMFRAMES=1			        GROUP=Takehit   // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Taunt1      STARTFRAME=150      NUMFRAMES=16    RATE=15	    Group=Gesture   // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Thrust      STARTFRAME=150      NUMFRAMES=16    RATE=15	    Group=Gesture   // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Breath2     STARTFRAME=290       NUMFRAMES=22    RATE=10    Group=Waiting   // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Breath2L    STARTFRAME=290       NUMFRAMES=22    RATE=10    Group=Waiting   // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Look        STARTFRAME=290       NUMFRAMES=22    RATE=10     Group=Waiting   // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=LookL       STARTFRAME=290       NUMFRAMES=22    RATE=10     Group=Waiting   // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Walk        STARTFRAME=182      NUMFRAMES=7    RATE=15                     // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=WalkLg      STARTFRAME=182      NUMFRAMES=7    RATE=15                     // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=WalkLgFr    STARTFRAME=182      NUMFRAMES=7    RATE=15     Group=MovingFire// :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=WalkSm      STARTFRAME=182      NUMFRAMES=7    RATE=15                     // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=WalkSmFr    STARTFRAME=182      NUMFRAMES=7    RATE=15     Group=MovingFire// :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=TurnLg      STARTFRAME=128      NUMFRAMES=2     RATE=15                     // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=TurnSm      STARTFRAME=128      NUMFRAMES=2     RATE=15                     // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=RunLg       STARTFRAME=182      NUMFRAMES=7     RATE=10                      // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=RunLgFr     STARTFRAME=182      NUMFRAMES=7     RATE=10	    Group=MovingFire// :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=RunSm       STARTFRAME=182      NUMFRAMES=7     RATE=10                      // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=RunSmFr     STARTFRAME=182      NUMFRAMES=7     RATE=10	    Group=MovingFire// :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=DuckWlkL    STARTFRAME=250      NUMFRAMES=16    RATE=15     Group=Ducking   // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=DuckWlkS    STARTFRAME=250      NUMFRAMES=16    RATE=15     Group=Ducking   // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=HeadHit     STARTFRAME=122      NUMFRAMES=1			        GROUP=Takehit   // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=RightHit    STARTFRAME=123      NUMFRAMES=1			        GROUP=Takehit   // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Dead1       STARTFRAME=38       NUMFRAMES=21    RATE=15
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Dead2       STARTFRAME=59       NUMFRAMES=16    RATE=15
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Dead4       STARTFRAME=99       NUMFRAMES=14    RATE=15
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=BigHit      STARTFRAME=102      NUMFRAMES=1
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Dead3       STARTFRAME=75       NUMFRAMES=24    RATE=15
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Victory1    STARTFRAME=157      NUMFRAMES=20    RATE=15     Group=Gesture
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=CockGun     STARTFRAME=228      NUMFRAMES=20    RATE=15     Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=CockGunL    STARTFRAME=228      NUMFRAMES=20    RATE=15     Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Wave        STARTFRAME=291      NUMFRAMES=20    RATE=15     Group=Gesture
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=WaveL       STARTFRAME=291      NUMFRAMES=20    RATE=15     Group=Gesture
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=LandLgFr    STARTFRAME=282      NUMFRAMES=8			        Group=Landing
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=LandSmFr    STARTFRAME=282      NUMFRAMES=8			        Group=Landing
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Run 	    STARTFRAME=162      NUMFRAMES=9     RATE=10             // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=BackRun     STARTFRAME=0        NUMFRAMES=38    RATE=32     Group=MovingFire    // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=StrafeL     STARTFRAME=184      NUMFRAMES=10    RATE=20     Group=MovingFire    // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=StrafeR     STARTFRAME=193      NUMFRAMES=9     RATE=20     Group=MovingFire    // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=SwimLg      STARTFRAME=142      NUMFRAMES=9     RATE=10                     // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=SwimSm      STARTFRAME=142      NUMFRAMES=9     RATE=10                     // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=TreadLg     STARTFRAME=162      NUMFRAMES=9     RATE=10     Group=Waiting   // :: FIX
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=TreadSm     STARTFRAME=162      NUMFRAMES=9     RATE=10     Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Fighter     STARTFRAME=121      NUMFRAMES=1
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=AimDnLg     STARTFRAME=124      NUMFRAMES=1			        Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=AimDnSm     STARTFRAME=124      NUMFRAMES=1			        Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=AimUpLg     STARTFRAME=124      NUMFRAMES=1			        Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=AimUpSm     STARTFRAME=124      NUMFRAMES=1			        Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=StillFrRp   STARTFRAME=132      NUMFRAMES=3	    RATE=10		Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=StillLgFr   STARTFRAME=279      NUMFRAMES=9    RATE=17		Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=StillSmFr   STARTFRAME=122      NUMFRAMES=12	RATE=17		Group=Waiting
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=JumpLgFr    STARTFRAME=44       NUMFRAMES=2			        Group=Jumping
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=JumpSmFr    STARTFRAME=44       NUMFRAMES=2			        Group=Jumping
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=DodgeB      STARTFRAME=117      NUMFRAMES=1			        Group=Jumping
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=DodgeF      STARTFRAME=118      NUMFRAMES=1			        Group=Jumping
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=DodgeR      STARTFRAME=120      NUMFRAMES=1			        Group=Jumping
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=DodgeL      STARTFRAME=119      NUMFRAMES=1			        Group=Jumping
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=Flip        STARTFRAME=120      NUMFRAMES=3     Rate=15	    Group=Jumping
#exec MESH SEQUENCE MESH=TCowNewJRM SEQ=DEAD9       STARTFRAME=97       NUMFRAMES=3
*/
///#exec MESHMAP SCALE MESHMAP=TCowNewJRM X=0.063 Y=0.0432 Z=0.126

#exec MESH NOTIFY MESH=TCowNewJRM SEQ=RunLG TIME=0.25 FUNCTION=PlayFootStep
#exec MESH NOTIFY MESH=TCowNewJRM SEQ=RunLG TIME=0.75 FUNCTION=PlayFootStep
#exec MESH NOTIFY MESH=TCowNewJRM SEQ=RunLGFR TIME=0.25 FUNCTION=PlayFootStep
#exec MESH NOTIFY MESH=TCowNewJRM SEQ=RunLGFR TIME=0.75 FUNCTION=PlayFootStep
#exec MESH NOTIFY MESH=TCowNewJRM SEQ=RunSM TIME=0.25 FUNCTION=PlayFootStep
#exec MESH NOTIFY MESH=TCowNewJRM SEQ=RunSM TIME=0.75 FUNCTION=PlayFootStep
#exec MESH NOTIFY MESH=TCowNewJRM SEQ=RunSMFR TIME=0.25 FUNCTION=PlayFootStep
#exec MESH NOTIFY MESH=TCowNewJRM SEQ=RunSMFR TIME=0.75 FUNCTION=PlayFootStep
#exec MESH NOTIFY MESH=TCowNewJRM SEQ=StrafeL TIME=0.25 FUNCTION=PlayFootStep
#exec MESH NOTIFY MESH=TCowNewJRM SEQ=StrafeL TIME=0.75 FUNCTION=PlayFootStep
#exec MESH NOTIFY MESH=TCowNewJRM SEQ=StrafeR TIME=0.25 FUNCTION=PlayFootStep
#exec MESH NOTIFY MESH=TCowNewJRM SEQ=StrafeR TIME=0.75 FUNCTION=PlayFootStep
#exec MESH NOTIFY MESH=TCowNewJRM SEQ=BackRun TIME=0.25 FUNCTION=PlayFootStep
#exec MESH NOTIFY MESH=TCowNewJRM SEQ=BackRun TIME=0.75 FUNCTION=PlayFootStep
#exec MESH NOTIFY MESH=TCowNewJRM SEQ=Dead2 TIME=0.57 FUNCTION=LandThump
#exec MESH NOTIFY MESH=TCowNewJRM SEQ=Dead3 TIME=0.71 FUNCTION=LandThump


#exec TEXTURE IMPORT NAME=Texture FILE=Textures\Texture.PCX GROUP=Skins FLAGS=2
#exec MESHMAP SETTEXTURE MESHMAP=TCowNewJRM NUM=0 TEXTURE=Texture

#exec TEXTURE IMPORT NAME=jmCowBody.bmp FILE=Textures\jmCowBody.PCX GROUP=Skins FLAGS=2
#exec MESHMAP SETTEXTURE MESHMAP=TCowNewJRM NUM=1 TEXTURE=jmCowBody.bmp

#exec TEXTURE IMPORT NAME=cowpack.png FILE=Textures\cowpack.PCX GROUP=Skins FLAGS=2
#exec MESHMAP SETTEXTURE MESHMAP=TCowNewJRM NUM=2 TEXTURE=cowpack.png

#exec TEXTURE IMPORT NAME=COW_FACE FILE=Textures\COW_FACE.PCX GROUP=Skins FLAGS=2
#exec MESHMAP SETTEXTURE MESHMAP=TCowNewJRM NUM=3 TEXTURE=COW_FACE

defaultproperties
{
    DrawType=DT_Mesh
    Mesh=TCowNewJRM
}